export const CREATE_LOVED_ONE_REQUEST = 'CREATE_LOVED_ONE_REQUEST';
export const CREATE_LOVED_ONE_SUCCESS = 'CREATE_LOVED_ONE_SUCCESS';
export const CREATE_LOVED_ONE_FAILURE = 'CREATE_LOVED_ONE_FAILURE';

export const UPDATE_LOVED_ONE_REQUEST = 'UPDATE_LOVED_ONE_REQUEST';
export const UPDATE_LOVED_ONE_SUCCESS = 'UPDATE_LOVED_ONE_SUCCESS';
export const UPDATE_LOVED_ONE_FAILURE = 'UPDATE_LOVED_ONE_FAILURE';

export const FETCH_LOVED_ONE_REQUEST= 'FETCH_LOVED_ONE_REQUEST';
export const FETCH_LOVED_ONE_SUCCESS= 'FETCH_LOVED_ONE_SUCCESS';
export const FETCH_LOVED_ONE_FAILURE= 'FETCH_LOVED_ONE_FAILURE';

export const DELETE_LOVED_ONE_REQUEST = 'DELETE_LOVED_ONE_REQUEST';
export const DELETE_LOVED_ONE_SUCCESS = 'DELETE_LOVED_ONE_SUCCESS';
export const DELETE_LOVED_ONE_FAILURE = 'DELETE_LOVED_ONE_FAILURE';

export const AUTHORIZATION_FAILURE = 'AUTHORIZATION_FAILURE';