export const CREATE_LOVED_ONE_REQUEST = 'CREATE_LOVED_ONE_REQUEST';
export const CREATE_LOVED_ONE_SUCCESS = 'CREATE_LOVED_ONE_SUCCESS';
export const CREATE_LOVED_ONE_FAILURE = 'CREATE_LOVED_ONE_FAILURE';

export const UPDATE_LOVED_ONE_REQUEST = 'UPDATE_LOVED_ONE_REQUEST';
export const UPDATE_LOVED_ONE_SUCCESS = 'UPDATE_LOVED_ONE_SUCCESS';
export const UPDATE_LOVED_ONE_FAILURE = 'UPDATE_LOVED_ONE_FAILURE';

export const UPDATE_USER_TABLE_REQUEST = 'UPDATE_USER_TABLE_REQUEST';
export const UPDATE_USER_TABLE_SUCCESS = 'UPDATE_USER_TABLE_SUCCESS';
export const UPDATE_USER_TABLE_FAILURE = 'UPDATE_USER_TABLE_FAILURE';