export const FETCH_USER = 'FETCH_USER';
export const SET_USER = 'SET_USER';
export const UPDATE_EDIT_USER_PROFILE = 'UPDATE_EDIT_USER_PROFILE';
export const CHANGE_PROFILE_VALUES = 'CHANGE-PROFILE-VALUES';